services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file: ./backend/.env
    environment:
      - POSTGRES_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
